### ISSUE TITLE
Syncing modifier configs doesn't work as expected

### ISSUE THREAD

**Issue by Odgug** [BONNePlayground/VaultHuntersSyncServerConfig#2]
Modifiers are read from the registry, which is initialized from configs on load. Because syncing new modifier configs only syncs the config, the registry remains the same and the new configs dont work properly. Please add an option to refresh the registry on thr client on sync

**Comment by BONNe** [comment]
It is not only modifiers registry. It is actually all registries.
The reason why it does not refresh is because it was not intended to be used like this.

I will think about generic way how to do it, as I do not want to write per config sync. That should be VH dev team job.

**Comment by BONNe** [comment]
To clarify:
```
AbilitiesDescriptionsConfig.class
AbilitiesGUIConfig.class
AchievementConfig.class
AlchemyTableConfig.class
ArchetypeDescriptionsConfig.class
ForgeRecipesConfig.class
LootInfoConfig.class
OmegaSoulShardConfig.class
QuestConfig.class
SkillDescriptionsConfig.class
SoulShardConfig.class
VaultBossConfig.class
VaultGearWorkbenchConfig.class
VaultModifiersConfig.class
```
All these 14 mentioned configs do something extra after the configuration is read from a file.

My mod skips the readConfig() method that does it from file, and directly injects the value from server side. So it bypasses all `overrides` in these mentioned config holders.

I can see 2 ways how to solve it:
- custom implementation for all these 14 config readers.
- change how configs are loaded

With the first, I have issue that VH adds new config that has custom stuff, and I need to instantly make an update. Also, it means I need to separate by 2 different ways how configs are processed and need to somehow know it from config name.

The second part is what I could do. Currently, configs are loaded from the direct server packet by changing the config field in memory. 
In theory, I could make that server configs are stored in `/the_vault/<server>/` directory, and they are read from it. 
It would fix issue with these 14 classes, as the read method would be called, but would just point to different location of file.

**Comment by Odgug** [comment]
Second option sounds great, if thats problematic tho only a few of those do stuff on the client so u wont have to do too much specific implementation, but yeah its definetly much worse for future proofing

**Comment by BONNe** [comment]
Update 1.5.0 implements my second idea.
